inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
    
# コメント必須を無視
Documentation:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enable: false

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 150